# Use lightweight Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# copy application files
copy . .

# Expose port 8080
EXPOSE 8080

# Run the app
CMD ["python", "app.py"]





